### ISSUE TITLE
Pagination with custom_loop

### ISSUE THREAD

**Issue by tobaco** [Veraxus/nouveau#2]
Hi!

First, thanks for this nice and clean framework!

Is it possible to use the custom_loop function with a pagination (e.g. archive_nav)?
How would I do that?

Thanks!

**Comment by Veraxus** [comment]
This is on my to-dos for 1.0.

**Comment by tobaco** [comment]
Thanks!

**Comment by Veraxus** [comment]
Fixed in 1.0 - finally!
