### ISSUE TITLE
Wordpress 4.4

### ISSUE THREAD

**Issue by thegrid22593** [Veraxus/nouveau#5]
Hi Matt, not positive if this is Nouveau related but since upgrading to 4.4 I am getting the following errors when wanting to create posts within custom post types.

I know taxonomy term meta is new in 4.4. Not sure the cause of this. I am using Custom Post Type UI plugin and I have talked with the Michael Beckwith and he says the plugin doesn't have anything related with the new meta.

Any ideas on how to go about fixing the issue?

WordPress database error: [Table 'db209288_wp_spinoc.wp_termmeta' doesn't exist]
SELECT term_id, meta_key, meta_value FROM wp_termmeta WHERE term_id IN (3) ORDER BY meta_id ASC

Warning: Cannot modify header information - headers already sent by (output started at /nfs/c09/h03/mnt/209288/domains/spinoc.org/html/wp-includes/wp-db.php:1355) in /nfs/c09/h03/mnt/209288/domains/spinoc.org/html/wp-admin/post.php on line 197

Warning: Cannot modify header information - headers already sent by (output started at /nfs/c09/h03/mnt/209288/domains/spinoc.org/html/wp-includes/wp-db.php:1355) in /nfs/c09/h03/mnt/209288/domains/spinoc.org/html/wp-includes/pluggable.php on line 1228

**Comment by Veraxus** [comment]
WordPress 4.4 introduces an official {$prefix}termmeta table. According to your error, that table doesn't exist. You may need to re-run the WordPress database upgrade from `/wp-admin/upgrade.php`

**Comment by thegrid22593** [comment]
Yea I fixed it with a re-install.

Thanks man!

On Tue, Jan 19, 2016 at 3:48 PM, Matt van Andel <notifications@github.com>
wrote:

> WordPress 4.4 introduces an official {$prefix}termmeta table. According to
> your error, that table doesn't exist. You may need to re-run the WordPress
> database upgrade from /wp-admin/upgrade.php
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Veraxus/nouveau/issues/5#issuecomment-173026360>.
>



-- 
Garrett Sanderson
Front End Developer | UI/UX Designer
http://gsandersongraphics.com

Web/Graphic Designer/Social Media
The All-American Boys Chorus
http://taabc.org
