### ISSUE TITLE
bower.json - duplicate dependencies

### ISSUE THREAD

**Issue by jurchiks** [Veraxus/nouveau#7]
https://github.com/Veraxus/nouveau/blob/master/bower.json

```
  "dependencies": {
    "foundation-sites": "~6.1.2",
    "motion-ui": "~1.1.0",
    "foundation-sites": "~6.2.0",
    "motion-ui": "~1.2.2"
  }
```
Which versions are actually used?

**Comment by Veraxus** [comment]
It's always the latest (so Foundation 6.2.1 as on now). I've updated the bower file to reflect this.

**Comment by Veraxus** [comment]
Looks like this is also present in the official Zurb distribution. Reaching out for explanation.
